name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean --no-daemon

    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Build release APK (if release config exists)
      run: ./gradlew assembleRelease --no-daemon || echo "Release build skipped (no release config found)"
      continue-on-error: true

    - name: Upload release APK (if exists)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
      continue-on-error: true
