name: Unzip on Upload

on:
  push:
    paths:
      - 'chessbottap_project.zip'
  workflow_dispatch:

jobs:
  unzip-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare folder
        run: mkdir -p extracted-project

      - name: Unzip zip file
        run: unzip chessbottap_project.zip -d extracted-project

      - name: List contents
        run: ls -R extracted-project

      - name: Commit unzipped files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add extracted-project/
          git commit -m "Add unzipped project files"
          git push
