name: Unzip Existing Zip

on:
  workflow_dispatch:   # manual trigger

jobs:
  unzip-job:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Create output folder
      - name: Prepare folder
        run: mkdir -p extracted-project

      # 3️⃣ Unzip existing zip file
      - name: Unzip chessbottap_project.zip
        run: unzip chessbottap_project.zip -d extracted-project

      # 4️⃣ List contents (optional, just to check)
      - name: List unzipped files
        run: ls -R extracted-project
