name: Unzip and Upload Artifact

on:
  push:
    branches:
      - main
    paths:
      - 'chessbottap_project.zip'  # Zip file push hone par auto trigger

jobs:
  unzip-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Extract zip file
      - name: Extract zip file
        run: |
          unzip -o chessbottap_project.zip -d extracted-project
          ls -R extracted-project

      # 3️⃣ Upload extracted files as artifact
      - name: Upload extracted project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: unzipped-project
          path: extracted-project/
